INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0073195', 'Jaws', '1975', 'PG', '124 min', 'Adventure, Drama, Thriller', 'Steven Spielberg', 'Roy Scheider, Robert Shaw, Richard Dreyfuss, Lorraine Gary', "When a killer shark unleashes chaos on a beach community, it's up to a local sheriff, a marine biologist, and an old seafarer to hunt the beast down.", 'English', "https://m.media-amazon.com/images/M/MV5BMmVmODY1MzEtYTMwZC00MzNhLWFkNDMtZjAwM2EwODUxZTA5XkEyXkFqcGdeQXVyNTAyODkwOQ@@._V1_SX300.jpg"));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0068646', 'The Godfather', '1972', 'R', '175 min', 'Crime, Drama', 'Francis Ford Coppola', 'Marlon Brando, Al Pacino, James Caan, Richard S. Castellano', "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.", 'English, Italian, Latin', "https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg"));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0111161', 'The Shawshank Redemption', '1994', 'R', '142 min', 'Drama', 'Frank Darabont', 'Tim Robbins, Morgan Freeman, Bob Gunton, William Sadler', "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.", 'English', 'https://m.media-amazon.com/images/M/MV5BMDFkYTc0MGEtZmNhMC00ZDIzLWFmNTEtODM1ZmRlYWMwMWFmXkEyXkFqcGdeQXVyMTMxODk2OTU@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0110912', 'Pulp Fiction', '1994', 'R', '154 min', 'Crime, Drama', 'Quentin Tarantino', 'Tim Roth, Amanda Plummer, Laura Lovelace, John Travolta', "The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.", 'English, Spanish, French', '"https://m.media-amazon.com/images/M/MV5BNGNhMDIzZTUtNTBlZi00MTRlLWFjM2ItYzViMjE3YzI5MjljXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0034583', 'Casablanca', '1942', 'PG', '102 min', 'Drama, Romance, War', 'Michael Curtiz', 'Humphrey Bogart, Ingrid Bergman, Paul Henreid, Claude Rains', 'A cynical American expatriate struggles to decide whether or not he should help his former lover and her fugitive husband escape French Morocco.', 'https://m.media-amazon.com/images/M/MV5BY2IzZGY2YmEtYzljNS00NTM5LTgwMzUtMzM1NjQ4NGI0OTk0XkEyXkFqcGdeQXVyNDYyMDk5MTU@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0062622', '2001:A Space Odyssey', '1968', 'G', '149 min', 'Adventure, Sci-Fi', 'Stanley Kubrick', 'Keir Dullea, Gary Lockwood, William Sylvester, Daniel Richter', 'After discovering a mysterious artifact buried beneath the Lunar surface, mankind sets off on a quest to find its origins with help from intelligent supercomputer H.A.L. 9000.', 'English, Russian', 'https://m.media-amazon.com/images/M/MV5BMmNlYzRiNDctZWNhMi00MzI4LThkZTctMTUzMmZkMmFmNThmXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0076759', 'Star Wars: Episode IV - A New Hope', '1977', 'PG', '121 min', 'Action, Adventure, Fantasy, Sci-Fi', 'George Lucas', 'Mark Hamill, Harrison Ford, Carrie Fisher, Peter Cushing', "Luke Skywalker joins forces with a Jedi Knight, a cocky pilot, a Wookiee and two droids to save the galaxy from the Empire's world-destroying battle station, while also attempting to rescue Princess Leia from the mysterious Darth Vader." , 'English', 'https://m.media-amazon.com/images/M/MV5BNzVlY2MwMjktM2E4OS00Y2Y3LWE3ZjctYzhkZGM3YzA1ZWM2XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0088763', 'Back to the Future', '1985', 'PG', '116 min', 'Adventure, Comedy, Sci-Fi', 'Robert Zemeckis', 'Michael J. Fox, Christopher Lloyd, Lea Thompson, Crispin Glover', "Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean invented by his close friend, the eccentric scientist Doc Brown.", 'English', 'https://m.media-amazon.com/images/M/MV5BZmU0M2Y1OGUtZjIxNi00ZjBkLTg1MjgtOWIyNThiZWIwYjRiXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0082971', 'Raiders of the Lost Ark', '1981', 'PG', '115 min', 'Action, Adventure', 'Steven Spielberg', 'Harrison Ford, Karen Allen, Paul Freeman, Ronald Lacey', "In 1936, archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler's Nazis can obtain its deadly powers", 'English, German, Hebrew, Spanish, Arabic, Nepali', 'https://m.media-amazon.com/images/M/MV5BMjA0ODEzMTc1Nl5BMl5BanBnXkFtZTcwODM2MjAxNA@@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0109830', 'Forrest Gump', '1994', 'PG-13', '142 min', 'Drama, Romance', 'Robert Zemeckis', 'Tom Hanks, Rebecca Williams, Sally Field, Michael Conner Humphreys', "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other history unfold through the perspective of an Alabama man with an IQ of 75.", 'English', 'https://m.media-amazon.com/images/M/MV5BNWIwODRlZTUtY2U3ZS00Yzg1LWJhNzYtMmZiYmEyNmU1NjMzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0078788', 'Apocalypse Now', '1979', 'R', '147 min', 'Drama, Mystery, War', 'Francis Ford Coppola', 'Marlon Brando, Martin Sheen, Robert Duvall, Frederic Forrest', "A U.S. Army officer serving in Vietnam is tasked with assassinating a renegade Special Forces Colonel who sees himself as a god.", 'English, French, Vietnamese', 'https://m.media-amazon.com/images/M/MV5BMDdhODg0MjYtYzBiOS00ZmI5LWEwZGYtZDEyNDU4MmQyNzFkXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0075686', 'Annie Hall', '1977', 'PG', '93 min', 'Comedy, Romance', 'Woody Allen', 'Woody Allen, Diane Keaton, Tony Roberts, Carol Kane', "Neurotic New York comedian Alvy Singer falls in love with the ditzy Annie Hall.", 'English, German', "https://m.media-amazon.com/images/M/MV5BZDg1OGQ4YzgtM2Y2NS00NjA3LWFjYTctMDRlMDI3NWE1OTUyXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_SX300.jpg"));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0099685', 'Goodfellas', '1990', 'R', '146 min', 'Biography, Crime, Drama', 'Martin Scorsese', 'Robert De Niro, Ray Liotta, Joe Pesci, Lorraine Bracco', "The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.", 'English, Italian', 'https://m.media-amazon.com/images/M/MV5BY2NkZjEzMDgtN2RjYy00YzM1LWI4ZmQtMjIwYjFjNmI3ZGEwXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0071315', 'Chinatown', '1974', 'R', '130 min', 'Drama, Mystery, Thriller', 'Roman Polanski', '"Jack Nicholson, Faye Dunaway, John Huston, Perry Lopez', 'A private detective hired to expose an adulterer finds himself caught up in a web of deceit, corruption, and murder.', 'English, Cantonese, Spanish', 'https://m.media-amazon.com/images/M/MV5BOGMwYmY5ZmEtMzY1Yi00OWJiLTk1Y2MtMzI2MjBhYmZkNTQ0XkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_SX300.jpg'));
INSERT INTO movies (imbdid, title, year, rated, runtime, genre, director, actors, plot, language, poster ) VALUES (
('tt0102926', 'The Silence of the Lambs', '1992', 'R', '118 min', 'Crime, Drama, Thriller', 'Jonathan Demme', '"Jodie Foster, Lawrence A. Bonney, Kasi Lemmons, Lawrence T. Wrentz', "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.", "English, Latin", 'https://m.media-amazon.com/images/M/MV5BNjNhZTk0ZmEtNjJhMi00YzFlLWE1MmEtYzM1M2ZmMGMwMTU4XkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_SX300.jpg'));